name: eventevent
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences:
  dio: ^3.0.9
  flutter_placeholder_textlines:
  shimmer: ^1.0.1
  flutter_statusbarcolor: ^0.2.3
  path_provider:
  carousel_pro: ^1.0.0
  carousel_slider: ^1.3.0
  flutter_branch_sdk: ^0.1.3
  video_thumbnail: ^0.2.0
  mime:
  device_info: ^0.4.2+4
  photo_view: ^0.9.1
  sign_in_with_apple: ^2.5.1
  rate_my_app: ^0.5.0+3
  bloc: ^3.0.0
  place_picker: ^0.9.11
  liquid_progress_indicator:
  cached_network_image: 2.0.0-rc
  flutter_cupertino_date_picker: ^1.0.12
  image_picker: ^0.6.1+3
  image_cropper: ^1.0.2
  intl: ^0.15.8
  location: ^2.3.5
  geocoder: ^0.2.1
  flushbar: ^1.9.1
  jwt_decode: ^0.1.0
  auto_size_text: ^2.0.2+1
  marquee: ^1.3.0
  marquee_flutter: ^0.1.4
  flutter_money_formatter: ^0.8.2
  url_launcher: ^5.1.0
  uuid: ^2.0.2
  flutter_facebook_login: ^2.0.1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.0.4
  package_info: ^0.4.0+4
  settings_ui: ^0.2.0
  flutter_wowza: ^0.1.10
  googleapis: ^0.54.0
  firebase_crashlytics: ^0.1.0+3
  chewie: ^0.9.10
  googleapis_auth: any
  # lamp: ^0.0.6
  torch_compat: ^1.0.2
  native_device_orientation:
  clevertap_plugin: 1.1.2
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.2
  webview_flutter: ^0.3.15+1
  flutter_html: ^0.8.2
  flutter_barcode_scanner: ^0.1.5+1
  pie_chart: ^1.2.0
  launch_review: ^2.0.0
  flutter_screenutil:
  firebase_core: ^0.4.3+3
  flutter_local_notifications: ^1.2.2
  http_parser: ^3.1.3
  rxdart: ^0.23.0
  permission_handler: ^5.0.0+hotfix.5
  thumbnails: ^1.0.1
  csv: ^4.0.3
  uni_links: ^0.2.0
  video_player: ^0.10.2+3
  pull_to_refresh: ^1.5.6
  share_extend: ^1.1.0
  youtube_player_flutter: 6.0.3+2
  flutter_typeahead: ^1.7.0
  percent_indicator: ^2.1.1+1
  supernova_flutter_ui_toolkit: ^0.0.2
  mid_flutter: ^0.0.1
  sqflite: any
  rive: any
  screenshot: ^0.1.1
  flutter_credit_card:
  share: ^0.6.3+5
  camera: ^0.5.7+4
  page_indicator:
  flutter_playout: ^1.0.35
  web_socket_channel: ^1.1.0
  wakelock: ^0.1.4+1
  camera_with_rtmp: ^0.2.1
  # flutter_rtmp_publisher:
  #   git:
  #     url: git://github.com/OhYee/flutter_rtmp_publisher.git
  

  
  interactive_webview: ^0.1.2
  # apple_maps_flutter:
  #   git:
  #     url: https://github.com/LuisThein/apple_maps_flutter.git
#  flutter_svg: ^0.15.0
  flutter_date_pickers:
    path: flutter_date_pickers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path_android: "assets/icon_fix_eventevent.png"
  image_path_ios: "assets/eventevent_icon_baru.jpg"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/Proxima-Nova-Alt-Regular.ttf
        - asset: assets/fonts/Proxima_Nova_Thin_Italic.otf
          style: italic
        - asset: assets/fonts/Proxima-Nova-Alt-Bold.ttf
          weight: 700

  assets:
    - assets/flare/splashicon.flr
    - assets/flare/eventevent.flr
    - assets/flare/Spalsh_Eventevent.flr
    - assets/docs.png
    - assets/online-event.png
    - assets/icon_eventevent_kecil.png
    - assets/qr-code.png
    - assets/eventevent.png
    - assets/failed-transaction.png
    - assets/bottom-bar/home-white.png
    - assets/bottom-bar/home-green.png
    - assets/bottom-bar/notification-white.png
    - assets/bottom-bar/notification-green.png
    - assets/bottom-bar/new-something-white.png
    - assets/bottom-bar/new-something-green.png
    - assets/bottom-bar/user-white.png
    - assets/bottom-bar/user-green.png
    - assets/bottom-bar/timeline-white.png
    - assets/bottom-bar/timeline-green.png
    - assets/grey-fade.jpg
    - assets/btn_ticket/canceled.png
    - assets/btn_ticket/event-ended.png
    - assets/btn_ticket/free.png
    - assets/btn_ticket/free-limited.png
    - assets/btn_ticket/free-live-limited.png
    - assets/btn_ticket/going!.png
    - assets/btn_ticket/going.png
    - assets/btn_ticket/live.png
    - assets/btn_ticket/no-ticket.png
    - assets/btn_ticket/ots.png
    - assets/btn_ticket/ots-800px.png
    - assets/btn_ticket/paid.png
    - assets/btn_ticket/paid-live.png
    - assets/btn_ticket/paid-value.png
    - assets/icons/location-transparent.png
    - assets/icons/btn_love_small.png
    - assets/icons/btn_love_big.png
    - assets/icons/btn_loved_value.png
    - assets/icons/btn_chat.png
    - assets/icons/aset_icon/emedia.png
    - assets/icons/aset_icon/eventevent.png
    - assets/icons/aset_icon/notif.png
    - assets/icons/aset_icon/post.png
    - assets/icons/aset_icon/profile.png
    - assets/icons/aset_icon/timeline.png
    - assets/icons/aset_icon/home.png
    - assets/icons/aset_icon/latest.png
    - assets/icons/aset_icon/like.png
    - assets/icons/aset_icon/media.png
    - assets/icons/aset_icon/comment.png
    - assets/icons/aset_icon/popular.png
    - assets/icons/aset_icon/wowza_livestream.png
    - assets/icons/aset_icon/zoom_livestream.png
    - assets/icons/icon_apps/popular.png
    - assets/icons/icon_apps/home.png
    - assets/icons/icon_apps/wallet.png
    - assets/icons/icon_apps/qr.png
    - assets/icons/icon_apps/comment.png
    - assets/icons/icon_apps/latest.png
    - assets/icons/icon_apps/love.png
    - assets/icons/icon_apps/arrow.png
    - assets/icons/icon_apps/nearby.png
    - assets/icons/icon_apps/public_timeline.png
    - assets/icons/icon_apps/search.png
    - assets/icons/icon_apps/ticket.png
    - assets/icons/icon_apps/LivestreamTagIcon.png
    - assets/icons/icon_apps/edit.png
    - assets/icons/icon_apps/discover.png
    - assets/icons/icon_apps/delete.png
    - assets/icons/icon_apps/location.png
    - assets/icons/icon_apps/report.png
    - assets/icons/icon_apps/search.png
    - assets/icons/icon_apps/verif.png
    - assets/icons/icon_apps/play.png
    - assets/icons/icon_apps/play2.png
    - assets/icons/icon_apps/play.svg
    - assets/icons/icon_apps/illustrasi.png
    - assets/icons/icon_apps/announcement.png
    - assets/icons/icon_apps/paymentstatus.png
    - assets/icons/icon_apps/iconsettings.png
    - assets/icons/icon_apps/my_balance.png
    - assets/icons/btn_mail.png
    - assets/icons/btn_mail_active.png
    - assets/icons/btn_web.png
    - assets/icons/btn_web_active.png
    - assets/icons/btn_phone.png
    - assets/icons/btn_phone_active.png
    - assets/icons/btn_time_green.png
    - assets/icons/btn_gembok.png
    - assets/icons/Event_public.png
    - assets/icons/Event_private.png
    - assets/icons/checklist_green.png
    - assets/icons/btn_ok.png
    - assets/icons/btn_manage_ticket.png
    - assets/icons/btn_show_qr.png
    - assets/icons/btn_ticket_sales.png
    - assets/icons/butt_love_ijo.png
    - assets/icons/butt_eye.png
    - assets/icons/butt_share.png
    - assets/icons/butt_cowo.png
    - assets/icons/butt_cewe.png
    - assets/icons/butt_gender_apakah_ini.png
    - assets/white.png
    - assets/icons/btn_edit_profile.png
    - assets/icons/ic_logo_company.png
    - assets/icons/btn_follow.png
    - assets/icons/ticket.png
    - assets/icons/logo_company.png
    - assets/icons/btn_following.png
    - assets/icons/Icon_finish_create_event.png
    - assets/icons/page_post_event.png
    - assets/icons/page_post_media.png
    - assets/icons/post_livestream.png
    - assets/icons/icon_line.png
    - assets/icons/Icon_finish_create_event.png
    - assets/drawable/bca.png
    - assets/drawable/cam_switch.png
    - assets/drawable/flashlight.png
    - assets/drawable/bni.png
    - assets/drawable/bri.png
    - assets/drawable/btn.png
    - assets/drawable/facebook.png
    - assets/drawable/google.png
    - assets/drawable/danamon.png
    - assets/drawable/maybank.png
    - assets/drawable/panin.png
    - assets/drawable/permata.png
    - assets/drawable/backaccount.png
    - assets/drawable/cimb.jpg
    - assets/drawable/mandiri.png
    - assets/drawable/amex.png
    - assets/icons/empty_state/public_timeline.png
    - assets/icons/empty_state/history.png
    - assets/icons/empty_state/profile.png
    - assets/icons/empty_state/my_ticket.png
    - assets/icons/empty_state/notification.png
    - assets/icons/empty_state/error.png
    - assets/drawable/cimbniaga.png
    - assets/drawable/bank.png
    - assets/drawable/discover.png
    - assets/drawable/mastercard.png
    - assets/drawable/visa.png
    - assets/drawable/success.png
    - assets/drawable/failed.png
    - assets/drawable/password.png
    - assets/drawable/password-invalid.png
    - assets/drawable/password-valid.png
    - assets/drawable/show-password.png
    - assets/drawable/my_ticket_empty_state.png
    - assets/drawable/profile_empty_state.png
    - assets/drawable/my_ticket_empty_state.png
    - assets/drawable/event_empty_state.png
    - assets/drawable/username.png
    - assets/drawable/username-invalid.png
    - assets/drawable/username-valid.png
    - assets/drawable/cake.png
    - assets/drawable/ic_tutorial_1.png
    - assets/drawable/ic_tutorial_2.png
    - assets/drawable/ic_tutorial_3.png
    - assets/logo_eventevent.png
    - assets/map_bw.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
